services:
  - type: web
    name: fpscape
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    branch: master
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
